# Embeddings

In [6]:
import tensorflow

In [7]:
import numpy as np

In [9]:
import nltk

In [10]:
import numpy as np

embedding_size = 4
vocab_size = 10

embedding = np.arange(embedding_size * vocab_size, dtype='float')
embedding = embedding.reshape(vocab_size, embedding_size)
print(embedding)



[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]
 [ 12.  13.  14.  15.]
 [ 16.  17.  18.  19.]
 [ 20.  21.  22.  23.]
 [ 24.  25.  26.  27.]
 [ 28.  29.  30.  31.]
 [ 32.  33.  34.  35.]
 [ 36.  37.  38.  39.]]


In [11]:
i = 3
onehot = np.zeros(10)
onehot[i] = 1.
onehot



array([ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.])

In [12]:
embedding_vector = np.dot(onehot, embedding)
print(embedding_vector)

[ 12.  13.  14.  15.]


In [14]:
print(embedding[i])

[ 12.  13.  14.  15.]


In [15]:


from keras.layers import Embedding

embedding_layer = Embedding(
    output_dim=embedding_size, input_dim=vocab_size,
    input_length=1, name='my_embedding')



Using TensorFlow backend.


cannot import name 'hashtable'
cannot import name 'hashtable'


In [16]:
from keras.layers import Input
from keras.models import Model

x = Input(shape=[1], name='input')
embedding = embedding_layer(x)
model = Model(input=x, output=embedding)
model.output_shape

/usr/local/lib/python3.4/dist-packages/ipykernel_launcher.py:6: UserWarning: Update your `Model` call to the Keras 2 API: `Model(outputs=Tensor("my..., inputs=Tensor("in...)`
  


(None, 1, 4)

In [17]:
model.get_weights()

[array([[ -3.50170024e-02,   1.46673582e-02,  -1.10029466e-02,
          -4.41501252e-02],
        [  4.09990586e-02,   1.22301094e-02,   1.33356340e-02,
          -1.24842897e-02],
        [ -1.78231224e-02,   3.52747738e-05,  -3.47950943e-02,
          -4.71090153e-03],
        [  1.81424953e-02,  -3.17019597e-02,   2.95588113e-02,
          -9.67528671e-03],
        [ -3.97337787e-02,  -3.67866047e-02,   3.82656790e-02,
           4.73581292e-02],
        [ -1.07114799e-02,  -3.07969935e-02,  -1.69290192e-02,
           4.35567759e-02],
        [ -4.27932516e-02,   1.84376724e-02,   3.98277752e-02,
          -1.68595798e-02],
        [ -6.53654337e-03,   2.18075030e-02,  -2.13399660e-02,
           1.51520111e-02],
        [  2.66963728e-02,   1.79144628e-02,   6.84161112e-03,
          -2.98406929e-03],
        [ -2.30199452e-02,  -1.79452188e-02,  -3.79866138e-02,
           4.45313193e-02]], dtype=float32)]

In [18]:
model.predict([[0],
               [3]])

array([[[-0.035017  ,  0.01466736, -0.01100295, -0.04415013]],

       [[ 0.0181425 , -0.03170196,  0.02955881, -0.00967529]]], dtype=float32)

In [19]:
from keras.layers import Flatten

x = Input(shape=[1], name='input')

# Add a flatten layer to remove useless "sequence" dimension
y = Flatten()(embedding_layer(x))

model2 = Model(input=x, output=y)
model2.output_shape

/usr/local/lib/python3.4/dist-packages/ipykernel_launcher.py:8: UserWarning: Update your `Model` call to the Keras 2 API: `Model(outputs=Tensor("fl..., inputs=Tensor("in...)`
  


(None, 4)

In [20]:
model2.predict([[0],
                [3]])

array([[-0.035017  ,  0.01466736, -0.01100295, -0.04415013],
       [ 0.0181425 , -0.03170196,  0.02955881, -0.00967529]], dtype=float32)

# Explicit Feedback Neural Recommender Systems

In [24]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import os.path as op

from zipfile import ZipFile
try:
    from urllib.request import urlretrieve
except ImportError:  # Python 2 compat
    from urllib import urlretrieve


ML_100K_URL = "http://files.grouplens.org/datasets/movielens/ml-100k.zip"
ML_100K_FILENAME = ML_100K_URL.rsplit('/', 1)[1]
ML_100K_FOLDER = 'ml-100k'

if not op.exists(ML_100K_FILENAME):
    print('Downloading %s to %s...' % (ML_100K_URL, ML_100K_FILENAME))
    urlretrieve(ML_100K_URL, ML_100K_FILENAME)

if not op.exists(ML_100K_FOLDER):
    print('Extracting %s to %s...' % (ML_100K_FILENAME, ML_100K_FOLDER))
    ZipFile(ML_100K_FILENAME).extractall('.')

In [32]:
from setuptools  import 

SyntaxError: invalid syntax (<ipython-input-32-35c882bbc2cd>, line 1)

In [29]:

import pandas

cannot import name 'hashtable'


ImportError: cannot import name 'hashtable'

In [25]:
import pandas as pd

all_ratings = pd.read_csv(op.join(ML_100K_FOLDER, 'u.data'), sep='\t',
                          names=["user_id", "item_id", "rating", "timestamp"])
all_ratings.head()

cannot import name 'hashtable'


ImportError: cannot import name 'hashtable'